title: Chinh Duc La
url: ""
baseurl: ""

markdown: kramdown

# tracking_id: #

footer: yes
footer_url: "https://github.com/chechaohp"
footer_text: “Dream as if you will live forever. And live as if you will die today.” - James Dean

plugins: [jekyll-paginate] 
paginate: 5
paginate_path: posts/page:num/

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "Resume"
   link: "/resume.pdf"
 - name: "Contact"
   link: "/contact"
 - name: "Blogs"
   link: "/blog"

theme: jekyll-theme-cayman